### ISSUE TITLE
Error: write EPIPE

### ISSUE THREAD

**Issue by Oliveira-SanRamon** [ember-cli-deploy/ember-cli-deploy-s3#103]
I am using this plug-in for the first time I cannot find a resolution for the error I am seeing below.
tried multiple times always with the same error:

- Using AWS access key id and secret access key from config
- preparing to upload to S3 bucket `www2.finderscopus.com`
..... (many files are uploaded)
- ✔  crossdomain.xml
- ✔  assets/images/dash2-555744e6303184c63a75401c212f966c.png
- ✔  fonts/glyphicons-halflings-regular.eot
- ✔  assets/images/power-03-61a82f306ca714e8a0b4a6904f8af8df.png
- NetworkingError: write EPIPE
- Error: write EPIPE
    at exports._errnoException (util.js:1050:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:814:14)
|
+- didFail
NetworkingError: write EPIPE
Error: write EPIPE
    at exports._errnoException (util.js:1050:11)
|
Pipeline aborted

**Comment by lukemelia** [comment]
Closing for lack of activity.
