### ISSUE TITLE
Upgrade from 0.4.0 > 0.5+

### ISSUE THREAD

**Issue by Blackening999** [ember-cli-deploy/ember-cli-deploy-s3#75]
Hello,

recently I've been forced to upgrade to newer version of ember-cli-deploy and a lot of issues started to appear after upgrade:

1. $ ember deploy <env> worked much slower than it was in 0.4.0
2. I cannot even deploy to S3 now (reason I'm opening ticket here)

```bash
- RequestTimeout: Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed.
- RequestTimeout: Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed.
    at Request.extractError (/Users/black/Work/<project>/node_modules/aws-sdk/lib/services/s3.js:538:35)
    at Request.callListeners (/Users/black/Work/<project>/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/Users/black/Work/<project>/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/black/Work/<project>/node_modules/aws-sdk/lib/request.js:668:14)
    at Request.transition (/Users/black/Work/<project>/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/black/Work/<project>/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/black/Work/<project>/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/black/Work/<project>/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/black/Work/<project>/node_modules/aws-sdk/lib/request.js:670:12)
    at Request.callListeners (/Users/black/Work/<project>/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at Request.emit (/Users/black/Work/<project>/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/black/Work/<project>/node_modules/aws-sdk/lib/request.js:668:14)
    at Request.transition (/Users/black/Work/<project>/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/black/Work/<project>/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/black/Work/<project>/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/black/Work/<project>/node_modules/aws-sdk/lib/request.js:38:9)
RequestTimeout: Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed.

```

3. The docs for deploying with Lightning strategy still bad. The content is scoped by section but here's no tutorial which might save tons of time for users. For instance, I've used ember-lightning before. I've decided to use their docker version. Despite the fact you have to configure nginx reverse-proxy and to find out this unless you're lucky and someone mention it somewhere, you have to spend tons of time researching how to deploy app in a right way.

If I'll be lucky to succeed with the new version (0.5+, latest (0.6.4) to be precise) I think I can write such guide. Otherwise, plugins are the chunks of code that you cannot simply bundle up and run in 5-10mins like, I believe, it should be.

I will be much appreciated if you can take a look at this ticket
@lukemelia

**Comment by Blackening999** [comment]
By the way,
this row:

``` bash
Deploying [====🚀 -----] 58% [plugin: s3 -> upload]
```

takes about ~3-5 minutes before I can see the error mentioned above...
If it's slow - what happened during upgrade from 0.4.0? Previously it was no more than 30sec to upload

**Comment by achambers** [comment]
Hi @Blackening999 . Sorry to hear you're having some issues mate. Let's see if we can address them and get you up and running. Firstly, and most importantly, ember-cli-deploy basically received a complete overhaul between 0.4.x and 0.5.0. This means that your existing deploy.js file will likely need some tweaks and, more importantly, any plugins you were using previously will not work. But don't worry as there is generally a 1:1 replacement for any plugins you were using.

So, my first question to you is:

**Have you switched out the old plugins for the new 0.5+ compatible ones or are you still attempting to use the old ones?**

(just realised this very issue is on the new s3 plugin so I assume the answer to above is "yes you have")

**Comment by Blackening999** [comment]
Hey @achambers  ! Awesome that you can help me ! Much appreciated! 

Yes, I have upgraded everything:

Before:
```json
{

"ember-cli-deploy": "^0.4.3",
"ember-deploy-redis": "0.0.7",
"ember-deploy-s3": "0.0.5",

"dependencies": {
  "ember-deploy-s3-index": "^0.4.0"
}

}
```

After:

```json
{
    "ember-cli-deploy": "^0.6.4",
    "ember-cli-deploy-build": "0.1.1",
    "ember-cli-deploy-display-revisions": "0.2.2",
    "ember-cli-deploy-lightning-pack": "0.6.9",
    "ember-cli-deploy-manifest": "0.1.1",
    "ember-cli-deploy-redis": "0.4.1",
    "ember-cli-deploy-revision-data": "0.3.2",
    "ember-cli-deploy-s3": "0.4.0",

    "dependencies": {
      "ember-cli-deploy-s3-index": "^0.5.0"
    }
}
```

I have updated deploy.js as well to:

```js
/* jshint node: true */

var VALID_DEPLOY_TARGETS = [ //update these to match what you call your deployment targets
  'staging',
  'production'
];

module.exports = function(deployTarget) {
  var ENV = {
    build: {},
    pipeline: {
      activateOnDeploy: false
    },
    "revision-data": {
      "type": "version-commit"
    },
    redis: {
      keyPrefix: 'project-name',
      allowOverwrite: false
    },
    s3: {},
    's3-index': {},
    "verbose": true
  };

  if (VALID_DEPLOY_TARGETS.indexOf(deployTarget) === -1) {
    throw new Error('Invalid deployTarget ' + deployTarget);
  }

  if (deployTarget === 'staging') {
    ENV.redis.host = 'DOhostIP (external)';
    ENV.redis.port = 6379;
    ENV.redis.privateKey = '~/.ssh/id_rsa'; //not sure it work anymore
    ENV.redis.password = 'redis-pwd';

    ENV.s3.accessKeyId = 'id';
    ENV.s3.secretAccessKey = 'access-key';
    ENV.s3.bucket = 'bucket-name';
    ENV.s3.region = 'us-east-1';

    ENV["s3-index"].accessKeyId = 'id';
    ENV["s3-index"].secretAccessKey = 'access-key';
    ENV["s3-index"].bucket = 'bucket-name';
    ENV["s3-index"].region = 'us-east-1';
  }

//same for production. not mention here for brevity, my goal is to make it up and running for staing first

  return ENV;
};
```

Amazon S3 bucket configured properly with all required policies and CORSes :)

I have a DO instance where my nginx reverse-proxier resides with Redis onboard. I'm using ember-lightning. Also have some issues there, but I have a relevant topic there created. You can join into discussion anyway if you want to speed up process and if you know  how get around those issues :P 
https://github.com/philipheinser/ember-lightning/issues/15

Once I'm done with I'm gonna create a short guide (may be on ember-cli-deploy to scope all issue I've faced, so anyone else won't fall into similar issues)

**Comment by achambers** [comment]
@Blackening999 Ok, let's try and work through this one thing at a time.

## Installed plugins

You currently have `ember-cli-deploy-lightning-pack` installed, plus you have all the plugins installed explicitly as well. The point of the lightning pack is to include the plugins so you don't have to. So, you might want to remove the ones that you've explicitly installed there.

Also, you have the redis plugin installed and the s3-index plugin installed. Both of these are used for the same thing - to manage the index.html. You probably want to work out which one it is you're wanting to use and remove the other one.

## ember-lightning

I've not used this myself and it's really a separate issue to ember-cli-deploy and the deployment of your files as ember-lightning is simply the server that serves your index.html. Let's focus on getting your files deployed here.

## S3 error

The original error you posted seems to be coming from the aws-sdk. It seems to be timing out which is why it seems to take a long time for you. Can you please try running the deployment with the `--verbose` flag?

**Comment by achambers** [comment]
BTW - The lightning pack is used by many many people in production and has been for quite a long time so I suspect there is a problem with configuration, rather than the code. So, let's work through it and find out where the problem lies.

**Comment by lukemelia** [comment]
Closing for lack of activity.
